#!/bin/sh

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
insmod /ath9k_hw.ko
insmod /ath9k_common.ko
insmod /ath9k_htc.ko

ifconfig eth0 172.16.157.97
/sbin/sshd
mount -t nfs -o nolock 172.16.157.17:/home/howard/work/jz2440/nfs /mnt/nfs


